import turtle
import time
from turtle import *
import Screens
from Screens import *
turtle.register_shape("start.gif")
turtle.shape("start.gif")

turtle.bgpic("frame.gif")

player = Turtle()
player.hideturtle()
turtle.register_shape("story_player.gif")
player.shape("story_player.gif")

prince = Turtle()
prince.hideturtle()
turtle.register_shape("prince.gif")
prince.shape("prince.gif")

wizard = Turtle()
wizard.hideturtle()
turtle.register_shape("wizard.gif")
wizard.shape("wizard.gif")
wizard.pu()
wizard.goto(100,-250)

speech = Turtle()
speech.hideturtle()
turtle.register_shape("speech.gif")
speech.shape("speech.gif")
speech.pu()

queen = Turtle()
queen.hideturtle()
turtle.register_shape("queen.gif")
queen.shape("queen.gif")
queen.pu()
queen.goto(wizard.pos())


def intro(x,y):
	turtle.penup()
	turtle.hideturtle()
	turtle.write("Once upon a time, in a far away land,", align = ("center"), font = ("comic sans MS", 25, "bold"))
	time.sleep(2.5)
	turtle.clear()
	turtle.write("lived a princess and a prince.", align = ("center"), font = ("comic sans MS", 25, "bold"))
	time.sleep(2.5)
	characters_show()
	turtle.clear()
	turtle.write("One day, the dark queen came to the palace.", align = ("center"), font = ("comic sans MS", 25, "bold"))
	time.sleep(4)
	turtle.clear()
	queen.showturtle()
	turtle.write("She demanded to rule the kingdom, but the prince refused.", align = ("center"), font = ("comic sans MS", 20, "bold"))
	time.sleep(4)
	turtle.clear()
	turtle.write("She snapped her fingers...", align = ("center"), font = ("comic sans MS", 25, "bold"))
	time.sleep(4)
	turtle.clear()
	turtle.bgcolor("black")
	queen.hideturtle()
	turtle.color("white")
	player.hideturtle()
	prince.hideturtle()
	turtle.write("...and the palace went dark.", align = ("center"), font = ("comic sans MS", 25, "bold"))
	time.sleep(4)
	turtle.clear()
	turtle.bgcolor("white")
	turtle.color("black")
	player.showturtle()
	turtle.write("When the lights were back on, the prince was gone.", align = ("center"), font = ("comic sans MS", 25, "bold"))
	time.sleep(4)
	turtle.clear()
	speech.goto(player.xcor(), player.ycor() + 192)
	speech.showturtle()
	turtle.goto(speech.pos())
	turtle.write("I must find him!", align = ("center"), font = ("comic sans MS", 15, "bold"))
	time.sleep(4)
	turtle.clear()
	wizard.showturtle()
	speech.showturtle()
	speech.goto(100, wizard.ycor() + 183.5)
	turtle.goto(speech.pos())
	turtle.write("I will help you!", align = ("center"), font = ("comic sans MS", 15, "bold"))
	time.sleep(2.5)
	turtle.clear()
	turtle.write("ARE YOU READY?", align = ("center"), font = ("comic sans MS", 15, "bold"))
	time.sleep(4)
	turtle.clear()
	speech.goto(player.xcor(), player.ycor() + 192)
	turtle.goto(speech.pos())
	turtle.write("Yes!", align = ("center"), font = ("comic sans MS", 25, "bold"))
	time.sleep(4)
	turtle.clear()
	speech.hideturtle()
	player.hideturtle()
	wizard.hideturtle()
	import moveFunctions
	from moveFunctions import *
	import pygame
	wizard.goto(100,0)
	wizard.showturtle()
	wizard.shape("WizardStanding.gif")
	pygame.mixer.init() 
	pygame.mixer.music.load("Microsoft Windows XP Startup Sound.mp3")
	pygame.mixer.music.play(0,0.0)
	main()

	

def characters_show():
	player.pu()
	player.goto(-200, -250)
	player.showturtle()

	prince.pu()
	prince.goto(-100, -250)
	prince.showturtle()

